spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/vanset
spring.datasource.username=postgres
spring.datasource.password=Hindvansi@531102/4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
